language: csharp
dist: trusty
sudo: false

mono: none
dotnet: 2.1.401

addons:
  sonarcloud:
    organization: "teamspeakanalytics"

install:
  - dotnet restore

script:
  - dotnet build -c Release
  - sonar-scanner
