language: csharp
dist: trusty
sudo: false

mono: none
dotnet: 2.1.300

install:
  - dotnet restore ./src/TeamspeakAnalytics.hosting-and-backend.sln

script:
  - dotnet build -c Release ./src/TeamspeakAnalytics.hosting-and-backend.sln
